rucksacks = [
"WVHGHwddqSsNjsjwqVvdwZRCbcJcZTCcsZbLcJJsCZ",
"hngprFFhFDFhrDpzzQDhtnBJJRJZbZvTcvbfRCJfBRcBJl",
"DmptngtFwvvMmwmm",
"HFddrJnLdqtHBMQBmmVm",
"gbvNsbhsvQtmZTbQPT",
"vDshDlczcDhcssscwzQwslLJrSJLpqrrzpnCrSfLSnqq",
"pDGQDSpFDGzFDQSJqzDhjhQMTjTrwTstbTBTjTtLtbTMBT",
"zgzVNHHgMwMLbLNB",
"WRWPgdHCZccggJmJGzJmzGhGCD",
"sVJNlhldShpdpnnwVnwCwtwggt",
"WLFFcHWQLPPZQCgtnCgmbtbHwt",
"MPLWzRMMcGgRrWNDpSSSfDflMlTd",
"BBMZJcgBRjCZZzBpSvHQvbLvvHCQLQ",
"VlVTFwDTVGnfWSQPtsDPbvrpDS",
"wWdqhWlwGVfGwlfTVqFWfWWjzZZBJmMZMNdzZJMpjzNjgJ",
"FBWFphQBmDmpmMSpDWVcVcvsPcRbrjPMcMsr",
"HHtdnHnwNCHCTJRTPTzrbvVbcVRr",
"lHqHwlnlqnGCNGGmWDvvZfpZvG",
"mfVtmPtsccMmHcHCFfmhVmnpgZLbWPZqWnpqZbZWpgPW",
"zzvwBrzdQDvpZJfQJZJpLf",
"BrTBwRdNcfNmfStc",
"sTlhFLfZTTLcfsLlLDZflvQvRNqRJFNvRMRNvQQRBQ",
"CWcgwStWwCWWwvgNQvJBvQMQRB",
"wptGzbzGWVGSCVVlVlLDcVVsfhLTlf",
"HVnMVGwLLbsGnVsLnwLSBggMhjmgmgmhtmqhtgMhMj",
"zrZzJRZfzZfrPCrFcWccPdTdHHlvdmlgTghCtmtTgq",
"NFfcZWWzZrrHLBpBBGVGNG",
"HqFhhCBCBLmwwCqJCHFvvFdcprrrSSrjRFRjpgrggb",
"VGzWtQzGGQPVtlVNslVWsPdRpmcRrjpSzcrcbdSmSnSg",
"WPPGllQMPGmTLvLJBCwM",
"PvDWRSmTVvSvRhbZRpRpbjjjzM",
"GBFGHLglHrrrLgGrttbMjpbcpcZJBsBp",
"lrHgrrndgdNnlHGFQPMMmWPTvvWSCDQn",
"mmhQShhmhQfzNfTTlShbHJrRtltltJJtHlRLLZ",
"WscggNqwPWjcGcWWcpNcRJHHprZvZHrvtttZJpJr",
"jGjgcMGCwPNsGDCcszBfhhQQQDnFnTVVBV",
"mcGjrwzQcrZtQzZQDZcPssvPVVCPCVLwswwPBC",
"NJbqHddNSgdPWvvsVHVLPs",
"NqglNSlJFNSbSNdldNlNdNbTRFDrvRmQrQGtmDrvttQmmtDj",
"zzcBPnHBjgHjWJvbJQTvScbwcQ",
"qdspVCFqVqfFqLFCqtpTwtpTbSTbJpwBST",
"FRLFRCNNqMfdWNmZPBPZrHmm",
"VmtRRJmtrDrwhRcvPspltvgqtqsd",
"WGQBZzMMBGBGbZTTWWCMNSgggqnPlsfbqndndccglffg",
"CWQQZMFWdzMQdJJwJVFrwmmmRw",
"rZsFfGfNhznzsjhzZfVjGVvVdvSTSJHSDDtcmmmttC",
"wWpRBWlbWMWlQDvCcRSvJRSStm",
"LPlwWqbgwqjjcFshNf",
"lsppsGphmPrRQnvHdRpd",
"qBgjLqMjgjTLPnzHPrPRLnzv",
"gSMfNjNtttVbqBbtTSStjTqlhmlZDsDsbWZWFFFsGhlWPm",
"sPDPDzrGzBsGRsbwrjtSVvthVfQtQw",
"ClpgFZgNqMWCgqCpMNZqNWmNdtSwtljtVHQhtwfvdHtSdhSj",
"FpNCJpNcpfCpgNWPGBLcbTGTzTzPnG",
"mssNLCZqSqmNCHmrqHChJTjTjnRRnnqVnTTGngGTRn",
"dbwptFwQbvdtcvpZDcDddgzGPjTGgpPTRpzzzgRzTn",
"BwZdtZldDbrSsNrsrSHl",
"MLnFWMRWpnpnLnLCmPGTqQsFzBttTQ",
"SwNlDHNcddglSDBjrqmqGQqqmGtGGwszPP",
"vdSlNcrvvvnBMbBR",
"psZPRmTpRpgrlrDRBFgV",
"jvCqNhwnjhGNqCMqVgFHWtgHBrtwHFrJ",
"cGvbNcjvvhhjcvbQGcZdZSQpzdpmpPVpdZpd",
"drTHDdlHzllZDTzTQRQLsPPSsBbSjQdL",
"MfVVWmNvMnqNmVVpMMgfgMmvBFFfRRLQPPsPfsFLFCFRSFjR",
"whMnNVnqWmlllHswJTZT",
"ZSQTTLLlTsbmmDZlmNQSNFfPwHwqCjCCfjwFPwfwLr",
"MctMJMBVttnhJcBBVctwRHjHRJwJwjFfqPfRwj",
"vzqgqhBVzzTlZmmTlN",
"WgvlHJFvljvdBmzcvcwpmchc",
"TQqZsTZttLZbRZsLLMzzppBmNShCmBNTcNCN",
"LPMZsMZLMQVgglFPhFHlFl",
"qsBCPVPqVbwfnMQNmZJnqJgR",
"hHdrvvLWtvtjWQnZJTMrmpTZgN",
"DShSShLZdFGPGDPGsPsG",
"qRBddRzFFqFqHnNnPSnnmmSpgpJm",
"ssZDQMvvMwppNJWRDRpW",
"MMvwlsRMcQBjcLqLBBqc",
"ZGHpwFGvwpHrvfFTMtDfccMjntMntc",
"RgSCLRLJRSRSQQqJmTDMPMTtsJjnclBjtj",
"LVmmSSddLCwVHDbzDzZr",
"psgWdsBjnnJjbZWQDDLNrDcrLVQjLM",
"zPSCCHqCfqfmWNMcrVSLRM",
"TPHzWPFTGztqTGgdJdsssvZgwb",
"gcFgBChcClJjNCPb",
"sWZdZdrSmWmSZRwSmsvPlsTtTtNMnnlvnJJv",
"GSWrHZdGQpRrrSGmpWQmQfLfpVzDfghppzBVLBlBqg",
"BFNqFzBNhqVwmTtsqVst",
"dMwMwMfCMWbDtDvDssCC",
"ldMwMSHHMMWJpRpPLLpBzPZjgnZPhN",
"WczRJhcWggVBdzPPLnCjdvjm",
"lSpSTpTSsCCmmntNdp",
"wSFDCTwsGDqQqQVWWcJw",
"RqPqhDGBhRDrrhBFmPmbgssZbwbgCbwsmZsQ",
"nCtjMppjfTpjJJfVZwtzZtllLZwLss",
"MHfpMWdHpSCSfnSTJWhDDFDFBGqDGvvDBDFd",
"MCCGMCSHVGNTspVWQznddndg",
"rttLtvRbrhLZrbcQdJnnQdfddsrggf",
"BbRqltRtHsNNllNC",
"ncFpcsLLdFmWlRmnllTR",
"bMMVzVqMzjNVDblmRTPGlSmmPlqG",
"gNDDJMVZNCbNJNDNQCbZCbscvBsdBvrRHfcpdQpfFFff",
"VnWFbZvFbHWhFjZWVJZJLZFWTttpMCspQTTzQCHpgQMgztzT",
"dGcfdNdGrlRlBDGNSllfBMspgzmTgtQQgztMtzpmcT",
"lBNdqRsBRdfPNrLPFVVPVJPZZvhj",
"TLWgggJzwjgWgjgGnnmQnzQfNNNQsm",
"SpPbBlPBMlvFZpbbBmQGsmCJmCstsdNGBQ",
"MhSHhZPrPbvSFrJPpPMSbMcLjjqTLHDRTDDTTLDLTqgH",
"fprRRbbznFbcQVPDdQPdFV",
"LTvmsLmcsHmvDvSZDZVVSS",
"jWtmLccssJTLjHmLWWJwnwlBfwnBbllpCBnffbBr",
"plPBWzbnFLPPtGqMMwlMGwmS",
"ZQjDHjrQjdjVFwdMvCSfmwMqdt",
"DDhhrRDjQghHJjhWBbgbTccbsTzpWF",
"vgCbbwsTbWWWgwBWDGGDqtPGtMgGlFMH",
"znrznJNhLSLphRRRDlFPMmpFPjjHtMFF",
"llNcSQVSNcRbvCwwWcTdwZ",
"qpnJbnRRnJhRFhFHRgQSzHlSRHCCCg",
"fMBttBvsBjffvsQTtfGTWlCWsSgSmHCzZmLlHgzZ",
"ffMdjrfdwjfwwnhJPFchhqwQ",
"NCVSTCVCQCCRVDQSJsqFPsPNspFhhsgjPh",
"btvtWtcWnpgmFhjmmt",
"cfnffBfcWcrMdbvMQJDDrDTDVCpCDrGD",
"fZNhBWFSlFQFjWQTTldHgCwvTvqqdr",
"zznVzCznmHvnwgdH",
"PMMbCGPMDPcLbJhFhWhBhRScQZBQ",
"WQMrDWGHbSWHMNrTQRhghmgPZccmqDLwPqPg",
"svCzfpdzzdsnslCsnPZcHZPlJcqZgmqPPc",
"nntVpdpVsfjCHzvnsCzRTBrtWGbNNQSMbTNSRr",
"SnpDQdBqGpDSBMfQGcMQBDJPNstvJcWNsPJCtJtNRWPC",
"VrVHrhTHlPHTvvNtbhNRNswC",
"TzlFHHmrVlgTlTGSzGqpdMGBPQBS",
"zrCDnrDVCnCgnrHgGDnVVCZsNttQZmjtsmbMqGqsjbqj",
"TlRRWPSwwFwbSwTTTpNQQqNjqZZlmMMQQt",
"wvbwbRTLWdFFwvRBTbvTTRzrnznnJrDDCzBczBfHCJnz",
"SvTdmLNNNdvTBmvmLvSvDpgczzjfgjggpcjcNPzD",
"VJHQsJVlHpjjpzsjzP",
"VRlJbJQrVbVHJJPMhBdnBRCSLZZZnvnLvv",
"tMGcpGtMtLtsCGspLzNCBBmwCzQRzBBRWQ",
"hdlHFllDdZgDbDDlDHTWWTnzBBBvzmNHzwRz",
"FSddDlFRqDFqFSdPVqdhcfGMsVtVfLjrfGfjtMcs",
"RGMWnBMWfCCMBHTDptJJgZStRPmSRD",
"bqzFqjqcFLNLZZSmpSBgZZ",
"rFrQNbNBlNcbrQlNQvvclMswTCTCnwrwHrWGsGCswn",
"WLhJQddCQwRNCQNHczHNzMvZcZvcNc",
"SlSpSlrpDqnbqDjlGjGGljTjMZZPPMMfVPgfHMMVgVvqfgcw",
"SbGsDspbbnjTjBldCFmLwFCJLBmtJB",
"TMDjMvMqMvDTzcmFCgrJCr",
"ZZZJSZWVBHZWSSZQJhVhWnHJwczGGwGcCCFzwgmzcwFgwVzc",
"pLHNQSnNJsMLRJds",
"TsLZGwdsDFWHBZJFfZ",
"mqhRvqrzJRbmzJBFfgHHgWgHrrlH",
"JvvNhJmvtDdsNTwdLV",
"wwnSVSmwtbstznwgbzzVMTNpTNWdlCSlSWTffWNCSN",
"cFvccLGFGvvGHZflnNTpnZpZcB",
"GPqGDhGGqrDhVRgbnbttPmgs",
"rzSZJScLrcBLvjvsqMPZvjQl",
"nnpDqgDqFTgwqHHvMHvvvTvPMM",
"GnqCGpDqqVhccLmrmSmCRL",
"tJSTmdfddDTDJCPmbQvQLHvqqqbrbvlP",
"zWGsjcwwGGcVVjcGWcNjvNjQqrQtNFFQHHrF",
"RZnRVsswRsGWcwVBZVtBRdDJgCffTgmgfnnCpfTfTM",
"FnCrzhTrNPrMcnhMTnZZZNPwDPdbDmdDtwjdtjbmQwDt",
"sBvWrpppvLBsLRVBfHSfbbQmbwSjStDSwSwS",
"LVRRRJqqlHNlNTChrhMG",
"WNsfsstMvtMvNNGPZwmZmqZPLWZcww",
"rDCdDRCDFQjSVLcmZcDq",
"bBBHqTgBbQlQRCQFbgqdhvshGvTJMnfTtnnThnsN",
"VwWBTNQcVzDtrgfrtzzt",
"LLbpShLGvlbCmLjpGSCSCpvFdrgdddcHtrtGgfqHcDHqrd",
"pmvLmlpmjbLbpljJPBBcTBBQRZBBVJRZ",
"cVTcVTNvvghNhvggPPgtCVSpSQmzCqZDRCmDZDZS",
"dGJMWFsFMFWsnlzRlQzlzqpzlZzD",
"HdLFssFMsJbnbFjqbhPgjNggcrhg",
"LLVhQCTvRvmWlCppQfQQjPrwszNsfzNz",
"BZSgncHgnJStJHJgntMWzGsrPqGwsfPfGPwwwZ",
"bdBdJMBcShWCLbhWVC",
"vjdpGNGwSNCTwwRbfnWgQMLjQWMnLQ",
"DcmFPFtHmlcgpqWDnMbDLf",
"FZJPtcprHtPPHplZHPZclwwGBSZSvSwCwvZzNdwvvw",
"CdJLJCJPWPWcbtzJtqJzFrQvBhfjBBvjjvdjpFjr",
"sBRgsZGDNSBBRGDwphrrrThpHpgHvhpQ",
"DwDsGBDNwGmMNlMlMDSPmztJVCbVCCWqPqJLmW",
"LSTMgDSRSMHbMDWLHSvDScwtCGqGrjGrcLftqVGtVC",
"hzJPmlphCGrCwVrJ",
"zhPNdNnQZBZBhZnNZSgMWMDbMHwWSDWNDH",
"rcdvvcwvrHrMZBjHSZ",
"sDtWblgnltsDFlgFqltCCVQTMTgSHVTfSQfSHj",
"tDtRWFpFbWWWWNNDWsNqWvmzvhzhzGmzjjGvLwJmpc",
"nFSSnnbhSfgLSSnVjdjfHMgfMzGzmqlNGGmTPlqqTzTNNzlT",
"pBZsJJvccbBmlWGlNb",
"cvsssvZwsDwrDdfFgnbDfVbgng",
"mWRNWNCTdwdCwhCddbWWmhsZVgJQJBVBfsBsJQLQBLJb",
"qFFlGzFtjjcqzHtFtlRfVfsZfQHVfBHQRHgf",
"jqGjtcDnGnPzFRlzrnMdWrrCMMddNNWT",
"MHWCjjGMcHhbhPDLphHQ",
"nRVJrtgssdLgCppvLQbg",
"RlVVZNVRJlsstldsBCNlczfjjSZmWTcmGmTSfmSm",
"RTHqgTgMwgnGTRzqTHCGfdFdfhmBrJrdvbFJMhPB",
"lNZNNNLttLWJBPBdZBFmdZ",
"SppscpLVStclNPWtCczqnQQwHTTgCGwq",
"hSHRCbZRSZhbRZBctnMVjwwtWtwh",
"GrdFzQrDdJstjcWttwsF",
"drPJLDPGPvDvzrJPQLdDHpZlwLgRmwCHLpwgSbff",
"zMSSnCtCdSdCtdfMdHMdtVBDjhWDHBqbTVVBqhbDjr",
"cPNhFFNRlNDlTBqjlTBG",
"RvmvRpPNRgwgPvFwhmdCssmCzdMshMmL",
"tttjgrpTwmCgCwgwrrlrHzbzqqFNzdJqqZnddJwNbh",
"cQjMjPMBfcLBSjGQBndFnzNdNnhzzNGFbF",
"sSQPLMfVPBVSfBMvVLSPfHCttDjCDRRtrVVglgpttD",
"vdTvdpBvcTPdSSvCLrCCDLDCQGDl",
"sRfnFgmFRMVsnqgRmqzmrrDBDwtHlLHtrLCDGL",
"qRMVjJgRFnJfMssMsgZScPJpZbPbPPWhBZSp",
"ZJgNJhGZglMZZFDTPSNqFSqTSb",
"mwdvwpsjrcjBvpwFrvbHcDqbWHRWDSPWDHSR",
"CsvpsLLjFzhlLGFZ",
"sDNQrMrNfrlQjJRgGjbTllHG",
"ZRhSnWFVSwBtFRBVvVgHgbzjgGTJnngmGmHC",
"vWZLShhvZLVtSFSLqwVrQdqpcqMDddRNQMdsNP",
"hQhSQbbwtHzShwhSQPbJRsLwRCjJmDCcvmqCcs",
"FNdBTBTNMsRqqCjTjL",
"GNdrdMBVFShhSLSGGL",
"cZzcCmjjcvdzdWqgWTZgPZgZhh",
"wSwVGSJFTffgJTNh",
"FSVpVlBMShzbjzcpvp",
"qqlblClRbnTvqTmRqlmnTwrdfdwFFNrngfddDBrNtr",
"PcLcQLMVLGMzHLMchhLcjLFrrNrBfrfFNJtNgJDDBNzt",
"sSjjGcGQscSVSMjHVMSVPSQsWmCmppZCmtCWbbWTlZTqTl",
"qWlVJmDJHWJHVJlsdVTdhbFNNgFhwhhhFhwwZg",
"npjnvQpStCQLvBpPnvtBtBpGSGbzbGDggGNbgwghzZNGGN",
"jBvLtvjnrtMDmmDRTTrsWc",
"pmwdwzJtFmmlpFsWwtstJPGgvNgCCLWCvPgNNPQCQv",
"RfbfTRBnRGQvPNnncc",
"ZTbPZSDSBfSBVSbbBRbbbtrFdtlFmVsswtFwzdpszw",
"hVphQcmdcWWprWWhChFQBsfHjDTTBCHlSsTSBgSH",
"vqBRqqzbqMZPMwSTDjJjlHDllgHZ",
"PMnMLqtMnntQhWBccthB",
"vqqvCSvHSSwqvqCddnvQFmNbVjbJVVmGNNVHNNlH",
"pggrhzWgptWhZsmVlFmgNNVNbj",
"RzpMLLhhphtzrRrSSbQTBQwSTDBwQM",
"DSFQDlDFRddDHQHQtFlDVsVMTzrMCLSWZLZffSzLWrfCJz",
"jjBBvpgmbppBPbMwBBBNbbZWZzzCCTzzZgzWcJccLzWz",
"bvPwNwmpnBNhPmqpPvnwwNmtRQGQMdQDQlsGVVGhRlGFsl",
"SfJJwDJgpGdSGJNSTwTVJDRbWWfLtCWCLtRLHWrtbWBf",
"cQQPnFhjjQlczhqllhszhqsQRWnrbrHdHtbWrBWBbtvvHBrW",
"qMqqqqzFFmPjmmsFjmzsmhjcDGSZTJgTdpZwZgwSZVpMTNVG",
"czrcHMcMJtCCPnpFmH",
"DwGGlvLljGmDRdwLdLjfhtFsssnFVpfttpptsnFPnp",
"TlRTghTjwTDRTDlZZQgWMMrMJMSZmM",
"BzdNzNdgNNPfgdNsdQdNvVMLLVQVMcCRCMRmvCGc",
"zHpplwwZrZlqlWWrpZwqlHhLvqMCRDCGVmLcqGMVvCMmMD",
"rWrjwWwHplZbwpZtHtJJbgfFTfsNnBbsfbSdTzgB",
"jPRRppDLDGDTLLggMMjpLTGcrJWHsttJfwnWrMvrJnvnrNfJ",
"blqbzBdzmhhbQWnsNHtJvfssfd",
"lhFhzSzzSZVNSlVPgDPCPCGTRcGR",
"cqWcNWffPftvsvfpqPtZsBzrbmbFddBmbcLbdDHbHz",
"TJgljTnGgnLBTZbHdBFz",
"JgSnJwSlgGJRwMtfPtvfwsZQZZtv",
"hHhPbQPTwsdwdHqtgttjpNfjDt",
"FFlCmSzRCCmlzzRGCFNvRpvjvtZNZqsRfNRg",
"mVmsFMGFzJFBwQTMnMQndd",
"QQVpQGcVdGmspHHLtbqfqfbt",
"JvZTFDFzJzhFCWCZZDzWPBCJfLbnnwLqttnsHHNPwtbHLwjn",
"DssTMWvvvGMcQGQGld",
"sshRHZSZRbSZHhBFBMpMWpFgbbtb",
"JfjTjmwwTPvfTNPTQlmFFFqqmFMBBqFgFt",
"vDTvJffQTJjJvPvTNSHRzhCsShRRRDtZHz",
"NFLsRDNNDNBDlgPPgBglQlzj",
"HJhdZpfJzlWQjjHw",
"ffJTppZZqTNlGnNsMG",
"ZMrWcWwqqvPZMndGdqlnnDLnVT",
"HpCsshCfpFfHHJDDSlSVQQGGflDQ",
"zssNzRJFhjNHNNHpJRwbwMMzWWtZPcbBbwbG",
"HlNHHLHsBDRpHLlsHRlJnMhfWZMRnvCCCnWhZj",
"wtqSmQqttzSSQdPmmwZhChJjWJjPggCZCfZJ",
"SSwtTbTQmbtdqmGTTcfqzDLHFsBLDGLNGrsBHFGrLB",
"FFDvWznMWWMrPnPnWPgsmgQbhJRslHbwHwVVsVHjBsHb",
"ZtSffffpdLqpSCLfCNqfLqLCjHjHbwhpBwJllHlRVQllphjj",
"ZcNCtcGSctZScqfNGScLNcczPJFmzmDzGzWnrWFPFWDvrM",
"DnTPspmTPsTCDQWRZzZzZRCRfCfHfh",
"BNcqTBcFgbVchVJhVR",
"dTwdrBrwTSPPWnnmSmsn",
"pfbbDbHpNBFmQbpNNBSlLtlDStSdSPJLtLJR",
"ZcszvwgVCZswFzVTRTlTlRLgRJSWJR",
"jzZvVwFjcjjnwvzwZcjMpqMpbGQbQmhhHhmfHQmh",
"hTbddhQCtdNmdtwtdhTBbCddRSWscczwcRSWLJzcFJzDsFsR",
"NflgfPZPcgSLJcWD",
"lPVNZMMMpZlZZvfrMvpbQHQhtbtqdTQHthrqhd",
"JlWSStwhWJSRJpJvJBjTwTqcwTsDjsCTCB",
"dqFzgFZGGQNVmTcCrjrzsBrB",
"fdgLFQLnPdnqShRMPhlJMpWW",
"TMPcsPDjdDhsDcDcTTTDvdvghBNFGGtmNrSrgSSBGNtNFg",
"CVCbJqlRVVWWpRqRQZRWVWJZBtmSFGNmggGmtmmBFbrGMGMt",
"JRqHVJVCRLZWTjMnfLTPcfLd",
"TRTZFTTrghrZVhVWdWZpMmbzbdzBmtDpDDzmzB",
"wcsSSsjfPfGPqQwqsQcfJJCtJGpppCBJzCbzJzCb",
"sPjflcwljfjfvqNcTZTRhtVWrNrVLnrR",
"rVLLsmwmCWTmsCTdwQrdTmqWDjDHjNGNPbjDBPNDNsZRDBjH",
"cFcSvgJvfhfLnShtMJtPHRRvRbBBGBPNBHPbND",
"hgLcgcLpJSMwzmrmzqQrmp",
]

rucksacksExample = [
"vJrwpWtwJgWrhcsFMMfFFhFp",
"jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL",
"PmmdzqPrVvPwwTWBwg",
"wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn",
"ttgJtRGJQctTZtZT",
"CrZsJsPPZsGzwwsLwLmpwMDw",
]

def characterToPriority(c):
    priority = ord(c) - 64
    if priority <= 26:
        return priority + 26
    else:
        return priority - 32

# Part 1
priorities = 0

for r in rucksacks:
    halfone, halftwo = r[:int(len(r)/2)], r[int(len(r)/2):]
    items = {}

    for c in halfone:
        items[c] = True
    
    for c in halftwo:
        if c in items:
            priorities += characterToPriority(c)
            items.pop(c)

print(priorities)

# Part 2
badgePriorities = 0

for i in range(0, len(rucksacks), 3):
    bagone, bagtwo, bagthree = {}, {}, {}

    for c in rucksacks[i]:
        bagone[c] = True
    for c in rucksacks[i+1]:
        bagtwo[c] = True
    for c in rucksacks[i+2]:
        bagthree[c] = True

    for c in bagone.keys():
        if c in bagtwo.keys() and c in bagthree.keys():
            badgePriorities += characterToPriority(c)


print(badgePriorities)